export const SIGNIN_ROUTE = '/signin'
export const SIGHUP_ROUTE = '/signup'
export const HOME_ROUTE = '/home'
export const DICTIONARY_ROUTE = '/dictionary'
export const DICTIONARY_ID_ROUTE = '/dictionary/:id'
