export const SIGNIN_ROUTE = '/signin'
export const SIGHUP_ROUTE = '/signup'
export const HOME_ROUTE = '/home'
export const DICTIONARY_ROUTE = '/dictionary'
export const DICTIONARY_ID_ROUTE = '/dictionary/:id'

export const localStorageHideWord = 'wordHide'
export const localStorageHideReading = 'readingHide'
export const localStorageHideTranslation = 'translationHide'
export const localStorageTheme = 'theme'
export const localStorageAuth = 'auth'
export const themeLight = 'light'
export const themeDark = 'dark'
export const firestoreUsersCollection = 'users'
export const firestoreListOfKanjiCollection = 'listOfKanji'
export const firestoreListOfKanjiDocId = '7VvmVjbBL4A1T3tQh6jd'
export const firestoreLinesCollection = 'allLines'